Introduction
============

About
-----

This package is only to demonstrate repo structure.

NI created and supports this package.

Operating System Support
------------------------

``example_package`` supports Windows and Linux operating systems.

Python Version Support
----------------------

``example_package`` supports CPython 3.10+.

Installation
------------

You can directly install the ``example_package`` package using ``pip`` or by listing it as a dependency in
your project's ``pyproject.toml`` file.